name: Test Pysteps installation

env:
  MINIMAL_DEPENDENCIES: cython numpy jsmin jsonschema matplotlib netCDF4 opencv pillow pyproj scipy dask
  OPTIONAL_DEPENDENCIES: dask pyfftw cartopy h5py PyWavelets pygrib
  TEST_DEPENDENCIES: pytest pytest-cov codecov

on: [ push ]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.6" ] # ["3.6", "3.7", "3.8", "3.9"]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install gcc for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew update-reset
          brew update
          brew install gcc@9
          which gcc-9
          export CC=gcc-9
          export CXX=g++-9
          export CXX1X=g++-9
          gcc-9 --version

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: test-environment

      - name: Install dependencies
        env:
          PACKAGES: ${{env.MINIMAL_DEPENDENCIES}} ${{env.OPTIONAL_DEPENDENCIES}} ${{env.TEST_DEPENDENCIES}}
          PYSTEPS_DATA_PATH: ${{github.workspace}}/pysteps_data
        run: |
          conda install mamba
          mamba install ${{env.PACKAGES}} --name base
      - name: Install pysteps
        run: pip install ${GITHUB_WORKSPACE}
      - name: Download pysteps data
        env:
          PYSTEPS_DATA_PATH: ${{github.workspace}}/pysteps_data
        run: |
          python $GITHUB_WORKSPACE/ci/fetch_pysteps_data.py
      - name: Run tests
        env:
          PYSTEPSRC: ${{github.workspace}}/pysteps_data/pystepsrc
        run: |
          python -c "import pysteps; print(pysteps.__file__)"
          pytest --pyargs pysteps --cov=pysteps -ra;
        working-directory: ${{github.workspace}}/pysteps_data

