name: Test Pysteps installation

env:
  MINIMAL_DEPENDENCIES: cython numpy jsmin jsonschema matplotlib netCDF4 opencv pillow pyproj scipy dask
  OPTIONAL_DEPENDENCIES: dask pyfftw cartopy h5py PyWavelets pygrib
  TEST_DEPENDENCIES: pytest pytest-cov codecov

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update ${MINIMAL_DEPENDENCIES} ${OPTIONAL_DEPENDENCIES} ${TEST_DEPENDENCIES} --name base
      - name: Install pysteps
        run: $CONDA/bin/pip install ${GITHUB_WORKSPACE}        
      - name: Download pysteps data
        env:
          PYSTEPS_DATA_DIR=${GITHUB_WORKSPACE}/pysteps_data
        run: |
          $CONDA/bin/python ${GITHUB_WORKSPACE}/ci/fetch_pysteps_data.py


