name: Test Pysteps installation

env:
  MINIMAL_DEPENDENCIES: cython numpy jsmin jsonschema matplotlib netCDF4 opencv pillow pyproj scipy dask
  OPTIONAL_DEPENDENCIES: dask pyfftw cartopy h5py PyWavelets pygrib
  TEST_DEPENDENCIES: pytest pytest-cov codecov

on: [ push ]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest"] # [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.6" ] # ["3.6", "3.7", "3.8", "3.9"]
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}      
      - name: Install dependencies
        env:
          PACKAGES: ${{env.MINIMAL_DEPENDENCIES}} ${{env.OPTIONAL_DEPENDENCIES}} ${{env.TEST_DEPENDENCIES}}
          PYSTEPS_DATA_PATH: ${{github.workspace}}/pysteps_data
        run: |
          $CONDA/bin/conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
          $CONDA/bin/conda config --add channels conda-forge
          $CONDA/bin/conda install mamba
          $CONDA/bin/mamba install ${{env.PACKAGES}} --name base
      - name: Install pysteps
        run: $CONDA/bin/pip install ${GITHUB_WORKSPACE}
      - name: Download pysteps data
        env:
          PYSTEPS_DATA_PATH: ${{github.workspace}}/pysteps_data
        run: |
          $CONDA/bin/python $GITHUB_WORKSPACE/ci/fetch_pysteps_data.py
      - name: Run tests
        env:
          PYSTEPSRC: ${{github.workspace}}/pysteps_data/pystepsrc
        run: $CONDA/bin/pytest --pyargs pysteps --cov=pysteps -ra;
        working-directory: ${{env.HOME}}

