name: Test Pysteps installation

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: $CONDA/bin/conda env update --file environment_dev.yml --name base
      - name: Install pysteps
        run: $CONDA/bin/pip install ${GITHUB_WORKSPACE}        
      - name: Download pysteps data
        run: |
          export PYSTEPS_DATA_DIR=${GITHUB_WORKSPACE}/pysteps_data
          $CONDA/bin/python ${GITHUB_WORKSPACE}/ci/fetch_pysteps_data.py


